name: APK Compilation (Android)

on:
  workflow_dispatch: 

env:
  JAVA_VERSION: "17.x"
  FLUTTER_CHANNEL: "stable"

jobs:
  apk_compilation: 
    name: "APK Compilation"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Configure Java for Android build
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: "gradle" 

      # Cache Gradle files to speed up builds
      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Set up Flutter environment
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true

      # Install Flutter dependencies
      - name: Install Flutter Dependencies
        run: flutter pub get

      # Build APKs
      - name: Build APKs
        run: flutter build apk --debug --split-per-abi

      # Upload APKs
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apks
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-debug.apk
