name: Clear Workflow Artifacts

on:
  schedule:
    - cron: '0 * * * *' # Run every hour
  workflow_dispatch:

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    
    steps:
      - name: Delete Artifacts
        uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          expire-in: 0 # Delete all artifacts
